apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-app2-to-app2
  namespace: app2
spec:
  selector: color == 'red'
  ingress:
    - action: Allow
      protocol: TCP
      source:
        selector: color == 'blue'
      destination:
        ports:
          - 80
