apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-nginx-app1
spec:
  order: 20
  selector: app == 'nginx-app1'
  ingress:
    - action: Deny
      source:
        selector: allowed == 'nginx'
